### ISSUE TITLE
Feasible to add support for Roku "Options" "*"?  

### ISSUE THREAD

**Issue by TerryBas** [FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin#4]
Hi, Feasible to add support for Roku "Options" "*"?  Thanks.

**Comment by jeovanny315** [comment]
this would be great

**Comment by V3RYSC4RY** [comment]
I would also benefit from this feature! Thank you.

**Comment by FUNKYJASPER2** [comment]
I can look into this.

**Comment by FUNKYJASPER2** [comment]
Just added it, will be in the next update.

**Comment by TerryBas** [comment]
The updated feature works great, thank you! 

 

-Terry

**Comment by DeckStreamer** [comment]
Just found this forum and wanted to thank you for this. It was a huge help for me.
