### ISSUE TITLE
Plugin stopped working for no apparent reason, IP address confirmed

### ISSUE THREAD

**Issue by BlakeLivSim** [FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin#5]
I've used this plugin for a few works, worked great out of the box.  This morning when I powered on my machine though, I noticed this plugin had stopped working. 

None of the actions have any effect.  Have tried the following: 
1. Verified IP address matches on the TV vs plugin (made sure the TV's local IP address hadn't changed) 
2. Unplugged TV
3. Restarted Streamdeck app
4. Restarted PC. 
5. Uninstalled Roku Plugin, reinstall. 

Any ideas?

**Comment by V3RYSC4RY** [comment]
I'm having the same experience!
