### ISSUE TITLE
Unable to Install Plugin

### ISSUE THREAD

**Issue by Archive853** [FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin#7]
I'm having issues installing the plugin. I don't know if this is an issue with the Stream Deck software itself or the plugin file. Whatever the case I'm just here to report the issue and the steps I took to attempt to solve it.

The issue I run into is the plugin failing to install.
![UnableToInstall_ElgatoMarketplace](https://github.com/FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin/assets/82474903/dc309f50-ef1e-4c8a-898b-1e2c6a76b784)

I then tried to install the plugin file manually and that also failed.
![UnableToInstall_Github](https://github.com/FUNKYJASPER2/StreamDeck-Roku-Remote-Plugin/assets/82474903/7a2e066c-862e-4a88-9f88-17e88987bde1)

I tried addressing it by logging out and back into the Elgato Marketplace and Stream Deck software and that did nothing for me. 

Lastly, I tried reinstalling the Stream Deck software all together and that also failed.

**Comment by FUNKYJASPER2** [comment]
Just got around to seeing this and I will look into it.

**Comment by Leroylima96** [comment]
has there been any update to this? Im also having a similar issue

**Comment by FUNKYJASPER2** [comment]
The latest update (6.5.1 (19929)) for the stream deck application from Elgato should have fixed this issue. As such I will be closing this issue. If it is not fixed on your end, please do open another issue.
